i =10
try : 
	j = 10/2
	print (j)
except Exception as e:
	print("Error")
	print (e)
finally:
	print("Finally block")	
